// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/leonardovalentini/crypto-coins/crypto/service (interfaces: CoinsPriceService)
//
// Generated by this command:
//
//	mockgen -destination=../tests/mocks/service/mockCoinsPriceService.go -package=service github.com/leonardovalentini/crypto-coins/crypto/service CoinsPriceService
//

// Package service is a generated GoMock package.
package service

import (
	context "context"
	reflect "reflect"

	domain "github.com/leonardovalentini/crypto-coins/crypto/domain"
	dto "github.com/leonardovalentini/crypto-coins/crypto/dto"
	gomock "go.uber.org/mock/gomock"
)

// MockCoinsPriceService is a mock of CoinsPriceService interface.
type MockCoinsPriceService struct {
	ctrl     *gomock.Controller
	recorder *MockCoinsPriceServiceMockRecorder
	isgomock struct{}
}

// MockCoinsPriceServiceMockRecorder is the mock recorder for MockCoinsPriceService.
type MockCoinsPriceServiceMockRecorder struct {
	mock *MockCoinsPriceService
}

// NewMockCoinsPriceService creates a new mock instance.
func NewMockCoinsPriceService(ctrl *gomock.Controller) *MockCoinsPriceService {
	mock := &MockCoinsPriceService{ctrl: ctrl}
	mock.recorder = &MockCoinsPriceServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCoinsPriceService) EXPECT() *MockCoinsPriceServiceMockRecorder {
	return m.recorder
}

// GetPrices mocks base method.
func (m *MockCoinsPriceService) GetPrices(ctx context.Context, userId string, gpr *dto.GetPricesRequest) ([]domain.Price, *int, *domain.Summary, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPrices", ctx, userId, gpr)
	ret0, _ := ret[0].([]domain.Price)
	ret1, _ := ret[1].(*int)
	ret2, _ := ret[2].(*domain.Summary)
	ret3, _ := ret[3].(error)
	return ret0, ret1, ret2, ret3
}

// GetPrices indicates an expected call of GetPrices.
func (mr *MockCoinsPriceServiceMockRecorder) GetPrices(ctx, userId, gpr any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPrices", reflect.TypeOf((*MockCoinsPriceService)(nil).GetPrices), ctx, userId, gpr)
}

// JobPrices mocks base method.
func (m *MockCoinsPriceService) JobPrices(ctx context.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "JobPrices", ctx)
}

// JobPrices indicates an expected call of JobPrices.
func (mr *MockCoinsPriceServiceMockRecorder) JobPrices(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "JobPrices", reflect.TypeOf((*MockCoinsPriceService)(nil).JobPrices), ctx)
}
