// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/leonardovalentini/crypto-coins/crypto/service (interfaces: UserCoinService)
//
// Generated by this command:
//
//	mockgen -destination=../tests/mocks/service/mockUserCoinService.go -package=service github.com/leonardovalentini/crypto-coins/crypto/service UserCoinService
//

// Package service is a generated GoMock package.
package service

import (
	context "context"
	reflect "reflect"

	domain "github.com/leonardovalentini/crypto-coins/crypto/domain"
	dto "github.com/leonardovalentini/crypto-coins/crypto/dto"
	gomock "go.uber.org/mock/gomock"
)

// MockUserCoinService is a mock of UserCoinService interface.
type MockUserCoinService struct {
	ctrl     *gomock.Controller
	recorder *MockUserCoinServiceMockRecorder
	isgomock struct{}
}

// MockUserCoinServiceMockRecorder is the mock recorder for MockUserCoinService.
type MockUserCoinServiceMockRecorder struct {
	mock *MockUserCoinService
}

// NewMockUserCoinService creates a new mock instance.
func NewMockUserCoinService(ctrl *gomock.Controller) *MockUserCoinService {
	mock := &MockUserCoinService{ctrl: ctrl}
	mock.recorder = &MockUserCoinServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserCoinService) EXPECT() *MockUserCoinServiceMockRecorder {
	return m.recorder
}

// DeleteUserCoin mocks base method.
func (m *MockUserCoinService) DeleteUserCoin(ctx context.Context, userId, userCoinId string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteUserCoin", ctx, userId, userCoinId)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteUserCoin indicates an expected call of DeleteUserCoin.
func (mr *MockUserCoinServiceMockRecorder) DeleteUserCoin(ctx, userId, userCoinId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteUserCoin", reflect.TypeOf((*MockUserCoinService)(nil).DeleteUserCoin), ctx, userId, userCoinId)
}

// GetAllUserCoinsByUserId mocks base method.
func (m *MockUserCoinService) GetAllUserCoinsByUserId(ctx context.Context, id string) ([]domain.UserCoin, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllUserCoinsByUserId", ctx, id)
	ret0, _ := ret[0].([]domain.UserCoin)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllUserCoinsByUserId indicates an expected call of GetAllUserCoinsByUserId.
func (mr *MockUserCoinServiceMockRecorder) GetAllUserCoinsByUserId(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllUserCoinsByUserId", reflect.TypeOf((*MockUserCoinService)(nil).GetAllUserCoinsByUserId), ctx, id)
}

// NewUserCoin mocks base method.
func (m *MockUserCoinService) NewUserCoin(ctx context.Context, userId string, req dto.UserCoinRequest) (*dto.NewUserCoinResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewUserCoin", ctx, userId, req)
	ret0, _ := ret[0].(*dto.NewUserCoinResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// NewUserCoin indicates an expected call of NewUserCoin.
func (mr *MockUserCoinServiceMockRecorder) NewUserCoin(ctx, userId, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewUserCoin", reflect.TypeOf((*MockUserCoinService)(nil).NewUserCoin), ctx, userId, req)
}

// UpdateUserCoin mocks base method.
func (m *MockUserCoinService) UpdateUserCoin(ctx context.Context, userId, userCoinId string, req dto.UserCoinRequest) (*domain.UserCoin, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateUserCoin", ctx, userId, userCoinId, req)
	ret0, _ := ret[0].(*domain.UserCoin)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateUserCoin indicates an expected call of UpdateUserCoin.
func (mr *MockUserCoinServiceMockRecorder) UpdateUserCoin(ctx, userId, userCoinId, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateUserCoin", reflect.TypeOf((*MockUserCoinService)(nil).UpdateUserCoin), ctx, userId, userCoinId, req)
}
