// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/leonardovalentini/crypto-coins/lib/logger (interfaces: LoggerI)
//
// Generated by this command:
//
//	mockgen -destination=../tests/mocks/logger/mockLogger.go -package=logger github.com/leonardovalentini/crypto-coins/lib/logger LoggerI
//

// Package logger is a generated GoMock package.
package logger

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
	zap "go.uber.org/zap"
)

// MockLoggerI is a mock of LoggerI interface.
type MockLoggerI struct {
	ctrl     *gomock.Controller
	recorder *MockLoggerIMockRecorder
	isgomock struct{}
}

// MockLoggerIMockRecorder is the mock recorder for MockLoggerI.
type MockLoggerIMockRecorder struct {
	mock *MockLoggerI
}

// NewMockLoggerI creates a new mock instance.
func NewMockLoggerI(ctrl *gomock.Controller) *MockLoggerI {
	mock := &MockLoggerI{ctrl: ctrl}
	mock.recorder = &MockLoggerIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLoggerI) EXPECT() *MockLoggerIMockRecorder {
	return m.recorder
}

// Debug mocks base method.
func (m *MockLoggerI) Debug(message string, fields ...zap.Field) {
	m.ctrl.T.Helper()
	varargs := []any{message}
	for _, a := range fields {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "Debug", varargs...)
}

// Debug indicates an expected call of Debug.
func (mr *MockLoggerIMockRecorder) Debug(message any, fields ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{message}, fields...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Debug", reflect.TypeOf((*MockLoggerI)(nil).Debug), varargs...)
}

// Error mocks base method.
func (m *MockLoggerI) Error(message string, fields ...zap.Field) {
	m.ctrl.T.Helper()
	varargs := []any{message}
	for _, a := range fields {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "Error", varargs...)
}

// Error indicates an expected call of Error.
func (mr *MockLoggerIMockRecorder) Error(message any, fields ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{message}, fields...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Error", reflect.TypeOf((*MockLoggerI)(nil).Error), varargs...)
}

// Fatal mocks base method.
func (m *MockLoggerI) Fatal(message string, fields ...zap.Field) {
	m.ctrl.T.Helper()
	varargs := []any{message}
	for _, a := range fields {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "Fatal", varargs...)
}

// Fatal indicates an expected call of Fatal.
func (mr *MockLoggerIMockRecorder) Fatal(message any, fields ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{message}, fields...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Fatal", reflect.TypeOf((*MockLoggerI)(nil).Fatal), varargs...)
}

// Info mocks base method.
func (m *MockLoggerI) Info(message string, fields ...zap.Field) {
	m.ctrl.T.Helper()
	varargs := []any{message}
	for _, a := range fields {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "Info", varargs...)
}

// Info indicates an expected call of Info.
func (mr *MockLoggerIMockRecorder) Info(message any, fields ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{message}, fields...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Info", reflect.TypeOf((*MockLoggerI)(nil).Info), varargs...)
}

// SetCtx mocks base method.
func (m *MockLoggerI) SetCtx(ctx context.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetCtx", ctx)
}

// SetCtx indicates an expected call of SetCtx.
func (mr *MockLoggerIMockRecorder) SetCtx(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetCtx", reflect.TypeOf((*MockLoggerI)(nil).SetCtx), ctx)
}
