// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/leonardovalentini/crypto-coins/crypto/domain (interfaces: UserCoinRepository)
//
// Generated by this command:
//
//	mockgen -destination=../tests/mocks/domain/mockUserCoinRepository.go -package=domain github.com/leonardovalentini/crypto-coins/crypto/domain UserCoinRepository
//

// Package domain is a generated GoMock package.
package domain

import (
	context "context"
	reflect "reflect"

	domain "github.com/leonardovalentini/crypto-coins/crypto/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockUserCoinRepository is a mock of UserCoinRepository interface.
type MockUserCoinRepository struct {
	ctrl     *gomock.Controller
	recorder *MockUserCoinRepositoryMockRecorder
	isgomock struct{}
}

// MockUserCoinRepositoryMockRecorder is the mock recorder for MockUserCoinRepository.
type MockUserCoinRepositoryMockRecorder struct {
	mock *MockUserCoinRepository
}

// NewMockUserCoinRepository creates a new mock instance.
func NewMockUserCoinRepository(ctrl *gomock.Controller) *MockUserCoinRepository {
	mock := &MockUserCoinRepository{ctrl: ctrl}
	mock.recorder = &MockUserCoinRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserCoinRepository) EXPECT() *MockUserCoinRepositoryMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockUserCoinRepository) Delete(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockUserCoinRepositoryMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockUserCoinRepository)(nil).Delete), ctx, id)
}

// FindAllByUserId mocks base method.
func (m *MockUserCoinRepository) FindAllByUserId(ctx context.Context, id string) ([]domain.UserCoin, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAllByUserId", ctx, id)
	ret0, _ := ret[0].([]domain.UserCoin)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAllByUserId indicates an expected call of FindAllByUserId.
func (mr *MockUserCoinRepositoryMockRecorder) FindAllByUserId(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAllByUserId", reflect.TypeOf((*MockUserCoinRepository)(nil).FindAllByUserId), ctx, id)
}

// FindBy mocks base method.
func (m *MockUserCoinRepository) FindBy(ctx context.Context, userId, coin, coinRef string) ([]domain.UserCoin, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindBy", ctx, userId, coin, coinRef)
	ret0, _ := ret[0].([]domain.UserCoin)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindBy indicates an expected call of FindBy.
func (mr *MockUserCoinRepositoryMockRecorder) FindBy(ctx, userId, coin, coinRef any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindBy", reflect.TypeOf((*MockUserCoinRepository)(nil).FindBy), ctx, userId, coin, coinRef)
}

// FindByUserCoinId mocks base method.
func (m *MockUserCoinRepository) FindByUserCoinId(ctx context.Context, userId, userCoinId string) (*domain.UserCoin, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByUserCoinId", ctx, userId, userCoinId)
	ret0, _ := ret[0].(*domain.UserCoin)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByUserCoinId indicates an expected call of FindByUserCoinId.
func (mr *MockUserCoinRepositoryMockRecorder) FindByUserCoinId(ctx, userId, userCoinId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByUserCoinId", reflect.TypeOf((*MockUserCoinRepository)(nil).FindByUserCoinId), ctx, userId, userCoinId)
}

// FindDifferentsCoins mocks base method.
func (m *MockUserCoinRepository) FindDifferentsCoins(ctx context.Context) ([]domain.UserCoin, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindDifferentsCoins", ctx)
	ret0, _ := ret[0].([]domain.UserCoin)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindDifferentsCoins indicates an expected call of FindDifferentsCoins.
func (mr *MockUserCoinRepositoryMockRecorder) FindDifferentsCoins(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindDifferentsCoins", reflect.TypeOf((*MockUserCoinRepository)(nil).FindDifferentsCoins), ctx)
}

// Save mocks base method.
func (m *MockUserCoinRepository) Save(ctx context.Context, u domain.UserCoin) (*domain.UserCoin, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", ctx, u)
	ret0, _ := ret[0].(*domain.UserCoin)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Save indicates an expected call of Save.
func (mr *MockUserCoinRepositoryMockRecorder) Save(ctx, u any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockUserCoinRepository)(nil).Save), ctx, u)
}

// Update mocks base method.
func (m *MockUserCoinRepository) Update(ctx context.Context, u domain.UserCoin) (*domain.UserCoin, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, u)
	ret0, _ := ret[0].(*domain.UserCoin)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockUserCoinRepositoryMockRecorder) Update(ctx, u any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockUserCoinRepository)(nil).Update), ctx, u)
}
