// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/leonardovalentini/crypto-coins/crypto/domain (interfaces: PriceRepository)
//
// Generated by this command:
//
//	mockgen -destination=../tests/mocks/domain/mockPriceRepository.go -package=domain github.com/leonardovalentini/crypto-coins/crypto/domain PriceRepository
//

// Package domain is a generated GoMock package.
package domain

import (
	context "context"
	reflect "reflect"

	domain "github.com/leonardovalentini/crypto-coins/crypto/domain"
	dto "github.com/leonardovalentini/crypto-coins/crypto/dto"
	gomock "go.uber.org/mock/gomock"
)

// MockPriceRepository is a mock of PriceRepository interface.
type MockPriceRepository struct {
	ctrl     *gomock.Controller
	recorder *MockPriceRepositoryMockRecorder
	isgomock struct{}
}

// MockPriceRepositoryMockRecorder is the mock recorder for MockPriceRepository.
type MockPriceRepositoryMockRecorder struct {
	mock *MockPriceRepository
}

// NewMockPriceRepository creates a new mock instance.
func NewMockPriceRepository(ctrl *gomock.Controller) *MockPriceRepository {
	mock := &MockPriceRepository{ctrl: ctrl}
	mock.recorder = &MockPriceRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPriceRepository) EXPECT() *MockPriceRepositoryMockRecorder {
	return m.recorder
}

// FindAllBy mocks base method.
func (m *MockPriceRepository) FindAllBy(ctx context.Context, userId string, gpr *dto.GetPricesRequest) ([]domain.Price, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAllBy", ctx, userId, gpr)
	ret0, _ := ret[0].([]domain.Price)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAllBy indicates an expected call of FindAllBy.
func (mr *MockPriceRepositoryMockRecorder) FindAllBy(ctx, userId, gpr any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAllBy", reflect.TypeOf((*MockPriceRepository)(nil).FindAllBy), ctx, userId, gpr)
}

// GetSummary mocks base method.
func (m *MockPriceRepository) GetSummary(ctx context.Context, userId string, gpr *dto.GetPricesRequest) (*int, *domain.Summary, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSummary", ctx, userId, gpr)
	ret0, _ := ret[0].(*int)
	ret1, _ := ret[1].(*domain.Summary)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetSummary indicates an expected call of GetSummary.
func (mr *MockPriceRepositoryMockRecorder) GetSummary(ctx, userId, gpr any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSummary", reflect.TypeOf((*MockPriceRepository)(nil).GetSummary), ctx, userId, gpr)
}

// Save mocks base method.
func (m *MockPriceRepository) Save(ctx context.Context, p domain.Price) (*domain.Price, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", ctx, p)
	ret0, _ := ret[0].(*domain.Price)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Save indicates an expected call of Save.
func (mr *MockPriceRepositoryMockRecorder) Save(ctx, p any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockPriceRepository)(nil).Save), ctx, p)
}
