// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/leonardovalentini/crypto-coins/crypto/domain (interfaces: BrokerSite)
//
// Generated by this command:
//
//	mockgen -destination=../tests/mocks/domain/mockBrokerSiteRepository.go -package=domain github.com/leonardovalentini/crypto-coins/crypto/domain BrokerSite
//

// Package domain is a generated GoMock package.
package domain

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockBrokerSite is a mock of BrokerSite interface.
type MockBrokerSite struct {
	ctrl     *gomock.Controller
	recorder *MockBrokerSiteMockRecorder
	isgomock struct{}
}

// MockBrokerSiteMockRecorder is the mock recorder for MockBrokerSite.
type MockBrokerSiteMockRecorder struct {
	mock *MockBrokerSite
}

// NewMockBrokerSite creates a new mock instance.
func NewMockBrokerSite(ctrl *gomock.Controller) *MockBrokerSite {
	mock := &MockBrokerSite{ctrl: ctrl}
	mock.recorder = &MockBrokerSiteMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBrokerSite) EXPECT() *MockBrokerSiteMockRecorder {
	return m.recorder
}

// GetName mocks base method.
func (m *MockBrokerSite) GetName() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetName")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetName indicates an expected call of GetName.
func (mr *MockBrokerSiteMockRecorder) GetName() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetName", reflect.TypeOf((*MockBrokerSite)(nil).GetName))
}

// GetPrice mocks base method.
func (m *MockBrokerSite) GetPrice(ctx context.Context, coin, coinRef string) (*float64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPrice", ctx, coin, coinRef)
	ret0, _ := ret[0].(*float64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPrice indicates an expected call of GetPrice.
func (mr *MockBrokerSiteMockRecorder) GetPrice(ctx, coin, coinRef any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPrice", reflect.TypeOf((*MockBrokerSite)(nil).GetPrice), ctx, coin, coinRef)
}
